### No compression
compress="lz4"



### Modules
# Only include necessary modules
hostonly=yes

# Btrfs dracut module
add_dracutmodules+=" btrfs "

# Omit resume (hibernate) module
#omit_dracutmodules+=" resume "

# Add resume (hibernate) module
add_dracutmodules+=" resume "

# Omit network
omit_dracutmodules+=" network "

# Omit plymouth
omit_dracutmodules+=" plymouth "



### Drivers
# Btrfs
add_drivers+=" btrfs "

# fat/vfat driver
add_drivers+=" fat vfat "

# Remove amdgpu (and asus drivers (?)) for better boot time
#omit_drivers+=" amdgpu asus_nb_wmi hid_asus asus_wmi "

# Force early loading of amdgpu
#add_drivers+=" amdgpu "
#force_drivers+=" amdgpu "
#install_items+=" /lib/firmware/amdgpu/* "

# Simpledrm
add_drivers+=" simpledrm "
force_drivers+=" simpledrm "

# Vfio
add_drivers+=" vfio_pci vfio vfio_iommu_type1 vendor_reset "
force_drivers+=" vfio_pci vfio vfio_iommu_type1 vendor_reset "

### Items
# Monitor specific edid
#install_items+=" /usr/lib/firmware/edid/zephg14.bin /usr/lib/firmware/edid/q27g3xmn.bin "



### Unified image
# Unified image
#uefi=yes

# Disable machine ID from filename
#machine_id=no



### Secure boot
# Keys for signing
uefi_secureboot_cert="/etc/refind.d/keys/refind_local.crt"
uefi_secureboot_key="/etc/refind.d/keys/refind_local.key"
